services:
  - type: web
    name: missionsync-backend
    runtime: php
    repo: https://github.com/GumbblOfficial/backend1212  # Reemplaza "tu-usuario"
    branch: main
    buildCommand: composer install
    startCommand: php index.php
    envVars:
      - key: TURSO_URL
        value: https://sync1212-branch-001-gumbblofficial.aws-us-east-1.turso.io  # Tu URL de Turso
      - key: TURSO_TOKEN
        sync: false  # Configura manualmente en Render
      - key: JWT_SECRET
        value: un-secreto-muy-seguro-12345
    plan: free
  - type: web
    name: missionsync-websocket
    runtime: php
    repo: https://github.com/GumbblOfficial/backend1212
    branch: main
    buildCommand: composer install
    startCommand: php websocket.php
    envVars:
      - key: TURSO_URL
        value: https://sync1212-branch-001-gumbblofficial.aws-us-east-1.turso.io
      - key: TURSO_TOKEN
        sync: false
    plan: free
